import { useState, useEffect } from 'react'
import type { ComponentInfo } from './useApi'

type LoadedComponents = Record<string, React.ComponentType<unknown>>

/**
 * Hook that loads signoz.io components from the virtual module generated by the Vite plugin.
 * The plugin parses MDXComponents.tsx and generates proper import statements.
 */
export function useSignozComponents(_componentInfos: ComponentInfo[]) {
  const [components, setComponents] = useState<LoadedComponents>({})
  const [isLoading, setIsLoading] = useState(true)
  const [errors, setErrors] = useState<Record<string, string>>({})

  useEffect(() => {
    async function loadComponents() {
      setIsLoading(true)
      const loadErrors: Record<string, string> = {}

      try {
        // Import the virtual module generated by vite-plugin-signoz-components
        const { loadSignozComponents } = await import('virtual:signoz-components')
        const loaded = await loadSignozComponents()

        console.log(
          `Loaded ${Object.keys(loaded).length} components from virtual module:`,
          Object.keys(loaded)
        )

        setComponents(loaded)
      } catch (err) {
        console.error('Failed to load signoz components:', err)
        loadErrors['_global'] = err instanceof Error ? err.message : 'Failed to load components'
      }

      setErrors(loadErrors)
      setIsLoading(false)
    }

    loadComponents()
  }, [])

  return { components, isLoading, errors }
}

/**
 * Get the component count (for display purposes when API info is available)
 */
export function useComponentCount(componentInfos: ComponentInfo[]) {
  return componentInfos.length
}
